// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: finance/v1/finance.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceClient interface {
	AddBalanceAccount(ctx context.Context, in *AddBalanceAccountReq, opts ...grpc.CallOption) (*AddBalanceAccountResp, error)
	AddBatchBalanceDetail(ctx context.Context, in *BalanceDetailReq, opts ...grpc.CallOption) (*BalanceDetailResp, error)
}

type balanceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceClient(cc grpc.ClientConnInterface) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) AddBalanceAccount(ctx context.Context, in *AddBalanceAccountReq, opts ...grpc.CallOption) (*AddBalanceAccountResp, error) {
	out := new(AddBalanceAccountResp)
	err := c.cc.Invoke(ctx, "/api.finance.v1.Balance/AddBalanceAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) AddBatchBalanceDetail(ctx context.Context, in *BalanceDetailReq, opts ...grpc.CallOption) (*BalanceDetailResp, error) {
	out := new(BalanceDetailResp)
	err := c.cc.Invoke(ctx, "/api.finance.v1.Balance/AddBatchBalanceDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServer is the server API for Balance service.
// All implementations must embed UnimplementedBalanceServer
// for forward compatibility
type BalanceServer interface {
	AddBalanceAccount(context.Context, *AddBalanceAccountReq) (*AddBalanceAccountResp, error)
	AddBatchBalanceDetail(context.Context, *BalanceDetailReq) (*BalanceDetailResp, error)
	mustEmbedUnimplementedBalanceServer()
}

// UnimplementedBalanceServer must be embedded to have forward compatible implementations.
type UnimplementedBalanceServer struct {
}

func (UnimplementedBalanceServer) AddBalanceAccount(context.Context, *AddBalanceAccountReq) (*AddBalanceAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBalanceAccount not implemented")
}
func (UnimplementedBalanceServer) AddBatchBalanceDetail(context.Context, *BalanceDetailReq) (*BalanceDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBatchBalanceDetail not implemented")
}
func (UnimplementedBalanceServer) mustEmbedUnimplementedBalanceServer() {}

// UnsafeBalanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceServer will
// result in compilation errors.
type UnsafeBalanceServer interface {
	mustEmbedUnimplementedBalanceServer()
}

func RegisterBalanceServer(s grpc.ServiceRegistrar, srv BalanceServer) {
	s.RegisterService(&Balance_ServiceDesc, srv)
}

func _Balance_AddBalanceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBalanceAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).AddBalanceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.finance.v1.Balance/AddBalanceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).AddBalanceAccount(ctx, req.(*AddBalanceAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_AddBatchBalanceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).AddBatchBalanceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.finance.v1.Balance/AddBatchBalanceDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).AddBatchBalanceDetail(ctx, req.(*BalanceDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Balance_ServiceDesc is the grpc.ServiceDesc for Balance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Balance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.finance.v1.Balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBalanceAccount",
			Handler:    _Balance_AddBalanceAccount_Handler,
		},
		{
			MethodName: "AddBatchBalanceDetail",
			Handler:    _Balance_AddBatchBalanceDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance/v1/finance.proto",
}
