// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: api/finance/v1/finance.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BalanceDetailReq) Reset() {
	*x = BalanceDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_finance_v1_finance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetailReq) ProtoMessage() {}

func (x *BalanceDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_finance_v1_finance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetailReq.ProtoReflect.Descriptor instead.
func (*BalanceDetailReq) Descriptor() ([]byte, []int) {
	return file_api_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceDetailReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BalanceDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BalanceDetailResp) Reset() {
	*x = BalanceDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_finance_v1_finance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetailResp) ProtoMessage() {}

func (x *BalanceDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_finance_v1_finance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetailResp.ProtoReflect.Descriptor instead.
func (*BalanceDetailResp) Descriptor() ([]byte, []int) {
	return file_api_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceDetailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_finance_v1_finance_proto protoreflect.FileDescriptor

var file_api_finance_v1_finance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x89, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x7e, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x61,
	0x64, 0x64, 0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42,
	0x26, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_finance_v1_finance_proto_rawDescOnce sync.Once
	file_api_finance_v1_finance_proto_rawDescData = file_api_finance_v1_finance_proto_rawDesc
)

func file_api_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_api_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_api_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_finance_v1_finance_proto_rawDescData)
	})
	return file_api_finance_v1_finance_proto_rawDescData
}

var file_api_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_finance_v1_finance_proto_goTypes = []interface{}{
	(*BalanceDetailReq)(nil),  // 0: api.finance.v1.BalanceDetailReq
	(*BalanceDetailResp)(nil), // 1: api.finance.v1.BalanceDetailResp
}
var file_api_finance_v1_finance_proto_depIdxs = []int32{
	0, // 0: api.finance.v1.Balance.AddBatchBalanceDetail:input_type -> api.finance.v1.BalanceDetailReq
	1, // 1: api.finance.v1.Balance.AddBatchBalanceDetail:output_type -> api.finance.v1.BalanceDetailResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_finance_v1_finance_proto_init() }
func file_api_finance_v1_finance_proto_init() {
	if File_api_finance_v1_finance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_finance_v1_finance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_finance_v1_finance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_finance_v1_finance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_api_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_api_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_api_finance_v1_finance_proto = out.File
	file_api_finance_v1_finance_proto_rawDesc = nil
	file_api_finance_v1_finance_proto_goTypes = nil
	file_api_finance_v1_finance_proto_depIdxs = nil
}
