// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: finance/v1/finance.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BalanceDetailReq) Reset() {
	*x = BalanceDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetailReq) ProtoMessage() {}

func (x *BalanceDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetailReq.ProtoReflect.Descriptor instead.
func (*BalanceDetailReq) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceDetailReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BalanceDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BalanceDetailResp) Reset() {
	*x = BalanceDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetailResp) ProtoMessage() {}

func (x *BalanceDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetailResp.ProtoReflect.Descriptor instead.
func (*BalanceDetailResp) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceDetailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddBalanceAccountDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 加盟商编码
	UpperOrganNo string `protobuf:"bytes,2,opt,name=upper_organ_no,json=upperOrganNo,proto3" json:"upper_organ_no,omitempty"`
	// 门店编码
	StoreCode string `protobuf:"bytes,1,opt,name=store_code,json=storeCode,proto3" json:"store_code,omitempty"`
	// 密码
	Pwd string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *AddBalanceAccountDetailReq) Reset() {
	*x = AddBalanceAccountDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBalanceAccountDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceAccountDetailReq) ProtoMessage() {}

func (x *AddBalanceAccountDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceAccountDetailReq.ProtoReflect.Descriptor instead.
func (*AddBalanceAccountDetailReq) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{2}
}

func (x *AddBalanceAccountDetailReq) GetUpperOrganNo() string {
	if x != nil {
		return x.UpperOrganNo
	}
	return ""
}

func (x *AddBalanceAccountDetailReq) GetStoreCode() string {
	if x != nil {
		return x.StoreCode
	}
	return ""
}

func (x *AddBalanceAccountDetailReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type AddBalanceAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountInfo *AddBalanceAccountDetailReq `protobuf:"bytes,1,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
}

func (x *AddBalanceAccountReq) Reset() {
	*x = AddBalanceAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBalanceAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceAccountReq) ProtoMessage() {}

func (x *AddBalanceAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceAccountReq.ProtoReflect.Descriptor instead.
func (*AddBalanceAccountReq) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{3}
}

func (x *AddBalanceAccountReq) GetAccountInfo() *AddBalanceAccountDetailReq {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

type AddBalanceAccountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddBalanceAccountResp) Reset() {
	*x = AddBalanceAccountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBalanceAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceAccountResp) ProtoMessage() {}

func (x *AddBalanceAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceAccountResp.ProtoReflect.Descriptor instead.
func (*AddBalanceAccountResp) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{4}
}

func (x *AddBalanceAccountResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 新增余额账户model
type AddBalanceAccountModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreCode    string `protobuf:"bytes,1,opt,name=storeCode,proto3" json:"storeCode,omitempty"`
	UpperOrganNo string `protobuf:"bytes,2,opt,name=upperOrganNo,proto3" json:"upperOrganNo,omitempty"`
	Pwd          string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *AddBalanceAccountModel) Reset() {
	*x = AddBalanceAccountModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_v1_finance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBalanceAccountModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceAccountModel) ProtoMessage() {}

func (x *AddBalanceAccountModel) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceAccountModel.ProtoReflect.Descriptor instead.
func (*AddBalanceAccountModel) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{5}
}

func (x *AddBalanceAccountModel) GetStoreCode() string {
	if x != nil {
		return x.StoreCode
	}
	return ""
}

func (x *AddBalanceAccountModel) GetUpperOrganNo() string {
	if x != nil {
		return x.UpperOrganNo
	}
	return ""
}

func (x *AddBalanceAccountModel) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

var File_finance_v1_finance_proto protoreflect.FileDescriptor

var file_finance_v1_finance_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2d, 0x0a, 0x11, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x73, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x0e, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x5f, 0x6e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x70, 0x70, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x4e, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x77, 0x64, 0x22, 0x65, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x4d, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x41,
	0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x6c, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x75, 0x70, 0x70, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x75, 0x70, 0x70, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x4e, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x77, 0x64, 0x32, 0x97, 0x02, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x8b,
	0x01, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x22, 0x13, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x3a, 0x0c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x7e, 0x0a, 0x15,
	0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x12, 0x18, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x2f,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x26, 0x0a, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finance_v1_finance_proto_rawDescOnce sync.Once
	file_finance_v1_finance_proto_rawDescData = file_finance_v1_finance_proto_rawDesc
)

func file_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(file_finance_v1_finance_proto_rawDescData)
	})
	return file_finance_v1_finance_proto_rawDescData
}

var file_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_finance_v1_finance_proto_goTypes = []interface{}{
	(*BalanceDetailReq)(nil),           // 0: api.finance.v1.BalanceDetailReq
	(*BalanceDetailResp)(nil),          // 1: api.finance.v1.BalanceDetailResp
	(*AddBalanceAccountDetailReq)(nil), // 2: api.finance.v1.AddBalanceAccountDetailReq
	(*AddBalanceAccountReq)(nil),       // 3: api.finance.v1.AddBalanceAccountReq
	(*AddBalanceAccountResp)(nil),      // 4: api.finance.v1.AddBalanceAccountResp
	(*AddBalanceAccountModel)(nil),     // 5: api.finance.v1.AddBalanceAccountModel
}
var file_finance_v1_finance_proto_depIdxs = []int32{
	2, // 0: api.finance.v1.AddBalanceAccountReq.account_info:type_name -> api.finance.v1.AddBalanceAccountDetailReq
	3, // 1: api.finance.v1.Balance.AddBalanceAccount:input_type -> api.finance.v1.AddBalanceAccountReq
	0, // 2: api.finance.v1.Balance.AddBatchBalanceDetail:input_type -> api.finance.v1.BalanceDetailReq
	4, // 3: api.finance.v1.Balance.AddBalanceAccount:output_type -> api.finance.v1.AddBalanceAccountResp
	1, // 4: api.finance.v1.Balance.AddBatchBalanceDetail:output_type -> api.finance.v1.BalanceDetailResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_finance_v1_finance_proto_init() }
func file_finance_v1_finance_proto_init() {
	if File_finance_v1_finance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finance_v1_finance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_v1_finance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_v1_finance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBalanceAccountDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_v1_finance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBalanceAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_v1_finance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBalanceAccountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_v1_finance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBalanceAccountModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finance_v1_finance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_finance_v1_finance_proto = out.File
	file_finance_v1_finance_proto_rawDesc = nil
	file_finance_v1_finance_proto_goTypes = nil
	file_finance_v1_finance_proto_depIdxs = nil
}
