// Code generated by ent, DO NOT EDIT.

package storebalanceaccount

const (
	// Label holds the string label denoting the storebalanceaccount type in the database.
	Label = "store_balance_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStoreCode holds the string denoting the store_code field in the database.
	FieldStoreCode = "store_code"
	// FieldUpperOrganNo holds the string denoting the upper_organ_no field in the database.
	FieldUpperOrganNo = "upper_organ_no"
	// FieldPwd holds the string denoting the pwd field in the database.
	FieldPwd = "pwd"
	// FieldPwdSalt holds the string denoting the pwd_salt field in the database.
	FieldPwdSalt = "pwd_salt"
	// FieldBalanceFee holds the string denoting the balance_fee field in the database.
	FieldBalanceFee = "balance_fee"
	// FieldTotalChargeFee holds the string denoting the total_charge_fee field in the database.
	FieldTotalChargeFee = "total_charge_fee"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the storebalanceaccount in the database.
	Table = "store_balance_accounts"
)

// Columns holds all SQL columns for storebalanceaccount fields.
var Columns = []string{
	FieldID,
	FieldStoreCode,
	FieldUpperOrganNo,
	FieldPwd,
	FieldPwdSalt,
	FieldBalanceFee,
	FieldTotalChargeFee,
	FieldIsDeleted,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
