// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"finance/internal/data/ent/predicate"
	"finance/internal/data/ent/storebalanceaccount"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreBalanceAccountDelete is the builder for deleting a StoreBalanceAccount entity.
type StoreBalanceAccountDelete struct {
	config
	hooks    []Hook
	mutation *StoreBalanceAccountMutation
}

// Where appends a list predicates to the StoreBalanceAccountDelete builder.
func (sbad *StoreBalanceAccountDelete) Where(ps ...predicate.StoreBalanceAccount) *StoreBalanceAccountDelete {
	sbad.mutation.Where(ps...)
	return sbad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sbad *StoreBalanceAccountDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sbad.hooks) == 0 {
		affected, err = sbad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StoreBalanceAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sbad.mutation = mutation
			affected, err = sbad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sbad.hooks) - 1; i >= 0; i-- {
			if sbad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sbad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sbad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbad *StoreBalanceAccountDelete) ExecX(ctx context.Context) int {
	n, err := sbad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sbad *StoreBalanceAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: storebalanceaccount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: storebalanceaccount.FieldID,
			},
		},
	}
	if ps := sbad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sbad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// StoreBalanceAccountDeleteOne is the builder for deleting a single StoreBalanceAccount entity.
type StoreBalanceAccountDeleteOne struct {
	sbad *StoreBalanceAccountDelete
}

// Exec executes the deletion query.
func (sbado *StoreBalanceAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := sbado.sbad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storebalanceaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sbado *StoreBalanceAccountDeleteOne) ExecX(ctx context.Context) {
	sbado.sbad.ExecX(ctx)
}
