// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"finance/internal/data/ent/predicate"
	"finance/internal/data/ent/storebalancechangedetail"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreBalanceChangeDetailDelete is the builder for deleting a StoreBalanceChangeDetail entity.
type StoreBalanceChangeDetailDelete struct {
	config
	hooks    []Hook
	mutation *StoreBalanceChangeDetailMutation
}

// Where appends a list predicates to the StoreBalanceChangeDetailDelete builder.
func (sbcdd *StoreBalanceChangeDetailDelete) Where(ps ...predicate.StoreBalanceChangeDetail) *StoreBalanceChangeDetailDelete {
	sbcdd.mutation.Where(ps...)
	return sbcdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sbcdd *StoreBalanceChangeDetailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sbcdd.hooks) == 0 {
		affected, err = sbcdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StoreBalanceChangeDetailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sbcdd.mutation = mutation
			affected, err = sbcdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sbcdd.hooks) - 1; i >= 0; i-- {
			if sbcdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sbcdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sbcdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbcdd *StoreBalanceChangeDetailDelete) ExecX(ctx context.Context) int {
	n, err := sbcdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sbcdd *StoreBalanceChangeDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: storebalancechangedetail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: storebalancechangedetail.FieldID,
			},
		},
	}
	if ps := sbcdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sbcdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// StoreBalanceChangeDetailDeleteOne is the builder for deleting a single StoreBalanceChangeDetail entity.
type StoreBalanceChangeDetailDeleteOne struct {
	sbcdd *StoreBalanceChangeDetailDelete
}

// Exec executes the deletion query.
func (sbcddo *StoreBalanceChangeDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := sbcddo.sbcdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storebalancechangedetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sbcddo *StoreBalanceChangeDetailDeleteOne) ExecX(ctx context.Context) {
	sbcddo.sbcdd.ExecX(ctx)
}
