// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"finance/internal/data/ent/predicate"
	"finance/internal/data/ent/storebalancechangedetail"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreBalanceChangeDetailQuery is the builder for querying StoreBalanceChangeDetail entities.
type StoreBalanceChangeDetailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StoreBalanceChangeDetail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StoreBalanceChangeDetailQuery builder.
func (sbcdq *StoreBalanceChangeDetailQuery) Where(ps ...predicate.StoreBalanceChangeDetail) *StoreBalanceChangeDetailQuery {
	sbcdq.predicates = append(sbcdq.predicates, ps...)
	return sbcdq
}

// Limit adds a limit step to the query.
func (sbcdq *StoreBalanceChangeDetailQuery) Limit(limit int) *StoreBalanceChangeDetailQuery {
	sbcdq.limit = &limit
	return sbcdq
}

// Offset adds an offset step to the query.
func (sbcdq *StoreBalanceChangeDetailQuery) Offset(offset int) *StoreBalanceChangeDetailQuery {
	sbcdq.offset = &offset
	return sbcdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sbcdq *StoreBalanceChangeDetailQuery) Unique(unique bool) *StoreBalanceChangeDetailQuery {
	sbcdq.unique = &unique
	return sbcdq
}

// Order adds an order step to the query.
func (sbcdq *StoreBalanceChangeDetailQuery) Order(o ...OrderFunc) *StoreBalanceChangeDetailQuery {
	sbcdq.order = append(sbcdq.order, o...)
	return sbcdq
}

// First returns the first StoreBalanceChangeDetail entity from the query.
// Returns a *NotFoundError when no StoreBalanceChangeDetail was found.
func (sbcdq *StoreBalanceChangeDetailQuery) First(ctx context.Context) (*StoreBalanceChangeDetail, error) {
	nodes, err := sbcdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storebalancechangedetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) FirstX(ctx context.Context) *StoreBalanceChangeDetail {
	node, err := sbcdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StoreBalanceChangeDetail ID from the query.
// Returns a *NotFoundError when no StoreBalanceChangeDetail ID was found.
func (sbcdq *StoreBalanceChangeDetailQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = sbcdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storebalancechangedetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := sbcdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StoreBalanceChangeDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StoreBalanceChangeDetail entity is found.
// Returns a *NotFoundError when no StoreBalanceChangeDetail entities are found.
func (sbcdq *StoreBalanceChangeDetailQuery) Only(ctx context.Context) (*StoreBalanceChangeDetail, error) {
	nodes, err := sbcdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storebalancechangedetail.Label}
	default:
		return nil, &NotSingularError{storebalancechangedetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) OnlyX(ctx context.Context) *StoreBalanceChangeDetail {
	node, err := sbcdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StoreBalanceChangeDetail ID in the query.
// Returns a *NotSingularError when more than one StoreBalanceChangeDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (sbcdq *StoreBalanceChangeDetailQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = sbcdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storebalancechangedetail.Label}
	default:
		err = &NotSingularError{storebalancechangedetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := sbcdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StoreBalanceChangeDetails.
func (sbcdq *StoreBalanceChangeDetailQuery) All(ctx context.Context) ([]*StoreBalanceChangeDetail, error) {
	if err := sbcdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sbcdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) AllX(ctx context.Context) []*StoreBalanceChangeDetail {
	nodes, err := sbcdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StoreBalanceChangeDetail IDs.
func (sbcdq *StoreBalanceChangeDetailQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := sbcdq.Select(storebalancechangedetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := sbcdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sbcdq *StoreBalanceChangeDetailQuery) Count(ctx context.Context) (int, error) {
	if err := sbcdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sbcdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) CountX(ctx context.Context) int {
	count, err := sbcdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sbcdq *StoreBalanceChangeDetailQuery) Exist(ctx context.Context) (bool, error) {
	if err := sbcdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sbcdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sbcdq *StoreBalanceChangeDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := sbcdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StoreBalanceChangeDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sbcdq *StoreBalanceChangeDetailQuery) Clone() *StoreBalanceChangeDetailQuery {
	if sbcdq == nil {
		return nil
	}
	return &StoreBalanceChangeDetailQuery{
		config:     sbcdq.config,
		limit:      sbcdq.limit,
		offset:     sbcdq.offset,
		order:      append([]OrderFunc{}, sbcdq.order...),
		predicates: append([]predicate.StoreBalanceChangeDetail{}, sbcdq.predicates...),
		// clone intermediate query.
		sql:    sbcdq.sql.Clone(),
		path:   sbcdq.path,
		unique: sbcdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccountID int32 `json:"account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StoreBalanceChangeDetail.Query().
//		GroupBy(storebalancechangedetail.FieldAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sbcdq *StoreBalanceChangeDetailQuery) GroupBy(field string, fields ...string) *StoreBalanceChangeDetailGroupBy {
	grbuild := &StoreBalanceChangeDetailGroupBy{config: sbcdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sbcdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sbcdq.sqlQuery(ctx), nil
	}
	grbuild.label = storebalancechangedetail.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccountID int32 `json:"account_id,omitempty"`
//	}
//
//	client.StoreBalanceChangeDetail.Query().
//		Select(storebalancechangedetail.FieldAccountID).
//		Scan(ctx, &v)
//
func (sbcdq *StoreBalanceChangeDetailQuery) Select(fields ...string) *StoreBalanceChangeDetailSelect {
	sbcdq.fields = append(sbcdq.fields, fields...)
	selbuild := &StoreBalanceChangeDetailSelect{StoreBalanceChangeDetailQuery: sbcdq}
	selbuild.label = storebalancechangedetail.Label
	selbuild.flds, selbuild.scan = &sbcdq.fields, selbuild.Scan
	return selbuild
}

func (sbcdq *StoreBalanceChangeDetailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sbcdq.fields {
		if !storebalancechangedetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sbcdq.path != nil {
		prev, err := sbcdq.path(ctx)
		if err != nil {
			return err
		}
		sbcdq.sql = prev
	}
	return nil
}

func (sbcdq *StoreBalanceChangeDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StoreBalanceChangeDetail, error) {
	var (
		nodes = []*StoreBalanceChangeDetail{}
		_spec = sbcdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*StoreBalanceChangeDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &StoreBalanceChangeDetail{config: sbcdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sbcdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sbcdq *StoreBalanceChangeDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sbcdq.querySpec()
	_spec.Node.Columns = sbcdq.fields
	if len(sbcdq.fields) > 0 {
		_spec.Unique = sbcdq.unique != nil && *sbcdq.unique
	}
	return sqlgraph.CountNodes(ctx, sbcdq.driver, _spec)
}

func (sbcdq *StoreBalanceChangeDetailQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sbcdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sbcdq *StoreBalanceChangeDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   storebalancechangedetail.Table,
			Columns: storebalancechangedetail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: storebalancechangedetail.FieldID,
			},
		},
		From:   sbcdq.sql,
		Unique: true,
	}
	if unique := sbcdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sbcdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storebalancechangedetail.FieldID)
		for i := range fields {
			if fields[i] != storebalancechangedetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sbcdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sbcdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sbcdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sbcdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sbcdq *StoreBalanceChangeDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sbcdq.driver.Dialect())
	t1 := builder.Table(storebalancechangedetail.Table)
	columns := sbcdq.fields
	if len(columns) == 0 {
		columns = storebalancechangedetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sbcdq.sql != nil {
		selector = sbcdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sbcdq.unique != nil && *sbcdq.unique {
		selector.Distinct()
	}
	for _, p := range sbcdq.predicates {
		p(selector)
	}
	for _, p := range sbcdq.order {
		p(selector)
	}
	if offset := sbcdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sbcdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StoreBalanceChangeDetailGroupBy is the group-by builder for StoreBalanceChangeDetail entities.
type StoreBalanceChangeDetailGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sbcdgb *StoreBalanceChangeDetailGroupBy) Aggregate(fns ...AggregateFunc) *StoreBalanceChangeDetailGroupBy {
	sbcdgb.fns = append(sbcdgb.fns, fns...)
	return sbcdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sbcdgb *StoreBalanceChangeDetailGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sbcdgb.path(ctx)
	if err != nil {
		return err
	}
	sbcdgb.sql = query
	return sbcdgb.sqlScan(ctx, v)
}

func (sbcdgb *StoreBalanceChangeDetailGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sbcdgb.fields {
		if !storebalancechangedetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sbcdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sbcdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sbcdgb *StoreBalanceChangeDetailGroupBy) sqlQuery() *sql.Selector {
	selector := sbcdgb.sql.Select()
	aggregation := make([]string, 0, len(sbcdgb.fns))
	for _, fn := range sbcdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sbcdgb.fields)+len(sbcdgb.fns))
		for _, f := range sbcdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sbcdgb.fields...)...)
}

// StoreBalanceChangeDetailSelect is the builder for selecting fields of StoreBalanceChangeDetail entities.
type StoreBalanceChangeDetailSelect struct {
	*StoreBalanceChangeDetailQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sbcds *StoreBalanceChangeDetailSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sbcds.prepareQuery(ctx); err != nil {
		return err
	}
	sbcds.sql = sbcds.StoreBalanceChangeDetailQuery.sqlQuery(ctx)
	return sbcds.sqlScan(ctx, v)
}

func (sbcds *StoreBalanceChangeDetailSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sbcds.sql.Query()
	if err := sbcds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
