// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StoreBalanceAccount is the predicate function for storebalanceaccount builders.
type StoreBalanceAccount func(*sql.Selector)

// StoreBalanceChangeDetail is the predicate function for storebalancechangedetail builders.
type StoreBalanceChangeDetail func(*sql.Selector)
