// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"finance/internal/biz"
	"finance/internal/conf"
	"finance/internal/data"

	// "finance/internal/data"
	"finance/internal/server"
	"finance/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	// balance
	balanceRepo := data.NewBalanceRepo(dataData, logger)
	balanceUsecase := biz.NewBalanceUsecase(balanceRepo, logger)
	balanceService := service.NewBalanceService(balanceUsecase)

	grpcServer := server.NewGRPCServer(confServer, balanceService, logger)
	httpServer := server.NewHTTPServer(confServer, balanceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
